### ISSUE TITLE
Language files: update for 1.1.0

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-ext-external-images-as-link#13]
- [x] German Casual
- [x] German Formal
- [x] English
- [x] Arabic @alhitary 
- [x] French @Galixte (language removed via https://github.com/phpbb-de/phpbb-ext-external-images-as-link/commit/bfec7acba4578c86beee1c5446e378b6f6868eaa )

**Comment by alhitary** [comment]
Dear Crizz0,
Sorry for delay
Plz here it is : https://github.com/phpbb-de/phpbb-ext-external-images-as-link/pull/15
