### ISSUE TITLE
HTTPS Url marked as external link

### ISSUE THREAD

**Issue by jbclot** [phpbb-de/phpbb-ext-external-images-as-link#27]
Hello,
An url with a domain name like this : uploads.tapatalk-cdn.com is not accepted by the extension and marked as external link.
Example : https://uploads.tapatalk-cdn.com/20181021/151963febd69578ac6284ae87e19c14a.jpg
See on this forum :
https://forum.cnewyork.net/viewtopic.php?f=9&t=63436&p=494817#p494817

Thanks

**Comment by Crizz0** [comment]
Hi,

I did test this just now and it works like charm in 1.2.0 with 3.2.3:
`[img]https://uploads.tapatalk-cdn.com/20181021/151963febd69578ac6284ae87e19c14a.jpg[/img]
`

How did you set the acp settings for this extension? 

Regards

**Comment by jbclot** [comment]
Thanks.
Actually it's because of the tapatalk plugin which remove https in the url for this specific domain name : uploads.tapatalk-cdn.com . So your plugin cannot manage this exception.
For example :  https://uploads.tapatalk-cdn.com/20181021/151963febd69578ac6284ae87e19c14a.jpg
is rewritten 
//uploads.tapatalk-cdn.com/20181021/151963febd69578ac6284ae87e19c14a.jpg

Regards

**Comment by Crizz0** [comment]
Why does it remove the https: at all?

**Comment by jbclot** [comment]
I don't know, but it's a mess! 
You can see on this page https://forum.cnewyork.net/viewtopic.php?f=9&t=63436&p=494817
First image with https://uploads.tapatalk-cdn.com is rewritten. Second image with a fake domain https:// uploads1.tapatalk-cdn.com is not rewritten.

**Comment by Crizz0** [comment]
Mhm, but I cannot patch this from my end 😕

**Comment by jbclot** [comment]
Sure, I understand, it's not a problem with your plugin. I will try to fix it with Tapatalk. Thanks! :)
