### ISSUE TITLE
Allow images from https:// sources

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-ext-external-images-as-link#9]
In relation to: https://www.phpbb.com/customise/db/extension/phpbb.de_external_images_as_link/support/topic/145816?p=435166#p435166 

Maybe we can improve the behavior, to display images from SSL sources and only display a link for Non-SSL images.

**Comment by gn36** [comment]
It should be possible to configure this behaviour, though if we do so.
